stages:
  - test

test-job:
  stage: test
  before_script:
    - apt-get update
    - apt-get install python3-pip -y
    - python3 -m pip install --upgrade pip
    - python3 -m pip install -r requirements.txt
  script:
    - echo "running testcases..."
    - python3 -m pytest tests/TestAssets.py
    - python3 -m pytest tests/TestCitizens.py
    - python3 -m pytest tests/TestPoints.py
    - python3 -m pytest tests/TestTile.py
    - python3 -m pytest tests/TestTime.py
  only:
    - master
    - develop
